#!/bin/bash
#
# Init file for SixSigns Tomcat server
#
# chkconfig: 2345 55 25
# description: SixSigns Tomcat server
#

# Source function library.
. /etc/init.d/functions

RUN_AS_USER=root # Adjust run user here
CATALINA_HOME=/usr/local/letstalk/console

start() {
	   pid=$(tomcat_pid)	  
       echo $pid		
		if [ -z "$pid" ]; then
			echo "Starting Tomcat: "
			if [ "x$USER" != "x$RUN_AS_USER" ]; then
			  su - $RUN_AS_USER -c "cd $CATALINA_HOME/bin;  sh startup.sh&"
			else
			    cd $CATALINA_HOME/bin
    			sudo sh startup.sh&
            fi
		echo "done......"
		else
		   echo tomcat already running......
		fi
        
}
stop() {
        echo "Shutting down Tomcat: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/shutdown.sh"
        else
          sudo $CATALINA_HOME/bin/shutdown.sh
        fi
		echo done...
        echo "done."
}
killcat() {       
		pid=$(tomcat_pid)	
		if [ -n "$pid" ]
		then
		 echo "Shutting down Tomcat: "		
			if [ "x$USER" != "x$RUN_AS_USER" ]; then
              su - $RUN_AS_USER -c "kill -9 $pid"
			else
              sudo kill -9 $pid
            fi
		echo done...
		else
			echo Tomcat Not running...
		fi
}
tomcat_pid() {
  echo `ps ax | grep $CATALINA_HOME | grep org.apache.catalina.startup.Bootstrap | awk '{print $1}'`
}
log(){
	tail -f $CATALINA_HOME/logs/catalina.out
}
rmlog(){
	rm -rf $CATALINA_HOME/logs/*
	echo logs deleted from $CATALINA_HOME/logs/
}
restart(){
	pid=$(tomcat_pid)	
	if [ -n "$pid" ]
		then
			echo "Tomcat is running with pid: $pid"
			echo stopping server...
			killcat			
			start
		else			
			start
	fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        killcat
        ;;
  restart)
        restart
        ;;
  kill)
        killcat
        ;;
  shutdown)
        stop
        ;;
  log)
        log
        ;;
  rmlog)
        rmlog
        ;;
  status)
        pid=$(tomcat_pid)
		if [ -n "$pid" ]
		then
			echo "Tomcat is running with pid: $pid"
		else
			echo "Tomcat is not running"
		fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|shutdown}"
esac

exit 0
